from tkinter import *
import customtkinter as ctk
Screen = Tk()
Screen.geometry("400x500")
ScreenWidth = Screen.winfo_screenwidth()
ScreenHeight = Screen.winfo_screenheight()
Screen.title("ATM Pin Setup Interface")
Screen.configure(bg="Red")
DetailsFrame = Frame(master=Screen, width=ScreenWidth, height=ScreenHeight, bg="Dark Red")
DetailsFrame.pack(pady=10)
UsernameEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = "Enter Your Username")
UsernameEntry.pack(pady=10)
PasswordEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, show="*", placeholder_text = " Enter Your Password ")
PasswordEntry.pack(pady=10)
AccountEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your Account Number ")
AccountEntry.pack(pady=10)
EmailEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your Email ID ")
EmailEntry.pack(pady=10)
FirstNameEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your First Name ")
FirstNameEntry.pack(pady=10)
LastNameEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your Last Name ")
LastNameEntry.pack(pady=10)
BirthDateEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your Birth Date ")
BirthDateEntry.pack(pady=10)
AddressEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, placeholder_text = " Enter Your Address ")
AddressEntry.pack(pady=10)
PinEntry = ctk.CTkEntry(DetailsFrame, width=ScreenWidth - 20, show="*", placeholder_text = " Enter Your PIN ")
PinEntry.pack(pady=10)
StatusLabel = ctk.CTkLabel(master=DetailsFrame, text="", font=("Arial", 12, "bold"))
StatusLabel.pack(pady=5)
def submit_form():
    entries = [UsernameEntry.get(), PasswordEntry.get(), AccountEntry.get(), EmailEntry.get(), FirstNameEntry.get(), LastNameEntry.get(), BirthDateEntry.get(), AddressEntry.get(), PinEntry.get(),]
    if any(field.strip() == "" for field in entries):
        StatusLabel.configure(text="Please fill in all the fields.", text_color="#ff4d4d")
    else:
        StatusLabel.configure(text="Your ATM Account has been set up successfully!", text_color="#4dff88")
SubmitBtn = Button(master=DetailsFrame, text="Set PIN", command=submit_form)
SubmitBtn.place(x = 10, y = 440)
Screen.mainloop()