from tkinter import *
Root = Tk()
Root.title(" Reading Schedule Planner ")
Root.geometry("1250x300")
Root.configure(bg = "Maroon")
Heading = Label(Root, text = " Reading Schedule Planner! ", font = ("Arial", 16, "bold"), bg = "Maroon", fg = "Red")
Instructions = Label(Root, text = " Enter the number of pages you plan to read each day and how many pages are in the book that you are currently reading in the window that opens when you click the button below! ", font = ("Arial", 12), bg = "Maroon", fg = "Red")
OpenWindowButton = Button(Root, text = " Open Window ", font = ("Arial", 12, "bold"), bg = "Maroon", fg = "Red", command = lambda: OpenWindow())
def OpenWindow():
    NewWindow = Toplevel(Root)
    NewWindow.title(" Reading Schedule Planner ")
    NewWindow.geometry("1250x300")
    NewWindow.configure(bg = "Maroon")
    PagesPerDayLabel = Label(NewWindow, text = " Enter the number of pages you plan to read each day: ", font = ("Arial", 12), bg = "Maroon", fg = "Red")
    PagesPerDayEntry = Entry(NewWindow, font = ("Arial", 12))
    TotalPagesLabel = Label(NewWindow, text = " Enter the total number of pages in the book you are currently reading: ", font = ("Arial", 12), bg = "Maroon", fg = "Red")
    TotalPagesEntry = Entry(NewWindow, font = ("Arial", 12))
    def CalculateSchedule(PagesPerDay, TotalPages):
        try:
            PagesPerDay = int(PagesPerDay)
            TotalPages = int(TotalPages)
            if PagesPerDay <= 0 or TotalPages <= 0:
                raise ValueError("Values must be positive integers.")
            DaysRequired = round(TotalPages / PagesPerDay)
            ResultLabel = Label(NewWindow, text = f" You will finish the book in approximately {DaysRequired} days! ", font = ("Arial", 12), bg = "Maroon", fg = "Red")
            ResultLabel.pack(pady = 10)
        except ValueError as e:
            ErrorLabel = Label(NewWindow, text = f" Error: {e} Please enter valid positive integers. ", font = ("Arial", 12), bg = "Maroon", fg = "Red")
            ErrorLabel.pack(pady = 10)
    CalculateButton = Button(NewWindow, text = " Calculate ", font = ("Arial", 12, "bold"), bg = "Maroon", fg = "Red", command = lambda: CalculateSchedule(PagesPerDayEntry.get(), TotalPagesEntry.get()))
    PagesPerDayLabel.pack(pady = 10)
    PagesPerDayEntry.pack(pady = 10)
    TotalPagesLabel.pack(pady = 10)
    TotalPagesEntry.pack(pady = 10)
    CalculateButton.pack(pady = 10)
Heading.pack(pady = 10)
Instructions.pack(pady = 10)
OpenWindowButton.pack(pady = 10)
Root.mainloop()